from toontown.toonbase.ToontownGlobals import SellbotFactoryExt, SellbotLobby, CashbotHQ, CashbotLobby,\
    LawbotOfficeExt, LawbotLobby, BossbotHQ, BossbotLobby

# Indexes

LEADER_NAME = 0
SHARD_NAME = 1
CATEGORY = 2
CURR_AVS = 3

# Category ID's

SELLBOT_FACTORY_FRONT = 0
SELLBOT_FACTORY_SIDE = 1
SELLBOT_VP = 2

CASHBOT_COIN_MINT = 10
CASHBOT_DOLLAR_MINT = 11
CASHBOT_BULLION_MINT = 12
CASHBOT_CFO = 13

LAWBOT_A_OFFICE = 20
LAWBOT_B_OFFICE = 21
LAWBOT_C_OFFICE = 22
LAWBOT_D_OFFICE = 23
LAWBOT_CJ = 24

BOSSBOT_FRONT_THREE = 30
BOSSBOT_MIDDLE_SIX = 31
BOSSBOT_BACK_NINE = 32
BOSSBOT_CEO = 33

ZONE_TO_CATEGORY_LIST = {
    SellbotFactoryExt: [SELLBOT_FACTORY_FRONT, SELLBOT_FACTORY_SIDE],
    SellbotLobby: [SELLBOT_VP, ],
    CashbotHQ: [CASHBOT_COIN_MINT, CASHBOT_DOLLAR_MINT, CASHBOT_BULLION_MINT],
    CashbotLobby: [CASHBOT_CFO, ],
    LawbotOfficeExt: [LAWBOT_A_OFFICE, LAWBOT_B_OFFICE, LAWBOT_C_OFFICE, LAWBOT_D_OFFICE],
    LawbotLobby: [LAWBOT_CJ, ],
    BossbotHQ: [BOSSBOT_FRONT_THREE, BOSSBOT_MIDDLE_SIX, BOSSBOT_BACK_NINE],
    BossbotLobby: [BOSSBOT_CEO, ],
}